spring:
  application:
    name: ThucHanh
  ai:
    openai:
      base-url: https://googleapis.com
      api-key:
      chat:
        model: gemini-flash-lite-latest

    datasource:
        url: jdbc:mysql://localhost:3306/ThucHanh?createDatabaseIfNotExist=true
        username: root
        password: 1234

    jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            show_sql: true
            format_sql: true
            dialect: org.hibernate.dialect.MySQLDialect